#  rate this menu
application: ratethismenu
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: .*
  script: Capstone.wsgi.application

libraries:
- name: django
  version: latest